# Generated by Django 5.2.1 on 2025-05-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_id_customuser_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
