# Generated by Django 5.2.1 on 2025-05-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_name_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='id',
        ),
    ]
