# Generated by Django 5.2.1 on 2025-05-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_groupmessage_groupmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['date_joined']},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
    ]
